version: '3'

vars:
  BINARY_NAME: autonix-go

tasks:
  build:
    desc: Build the binary
    cmds:
      - go build -o {{.BINARY_NAME}} main.go

  run:
    desc: Run the application
    cmds:
      - go run main.go

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - go clean
      - rm -f {{.BINARY_NAME}}

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  deps:
    desc: Download and tidy dependencies
    cmds:
      - go mod download
      - go mod tidy

  help:
    desc: List available tasks
    cmds:
      - task --list
